version: 2

updates:
  # Maintain Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain Docker dependency
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain root package.json dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain Backoffice SPA package.json dependencies
  - package-ecosystem: "npm"
    directory: "/src/main/backoffice"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
