version: 2

updates:
  # Keep terraform dependencies up to date
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"