version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/maintenance-page"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/opensearch/proxy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/backoffice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backoffice"
    schedule:
      interval: "weekly"
