version: "3.8"

services:
  beacons-service:
    build:
      context: ./
    container_name: beacons-service
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beacons

  postgres:
    image: library/postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: beacons_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beacons
