version: "3.8"

services:
  webapp:
    build:
      context: .
      target: nextjs-app
    ports:
      - "3000:3000"
    environment:
      API_URL: $API_URL
      GOV_NOTIFY_API_KEY: $GOV_NOTIFY_API_KEY
      BASIC_AUTH: $BASIC_AUTH
      AAD_API_ID: $AAD_API_ID
      AAD_TENANT_ID: $AAD_API_ID
      WEBAPP_CLIENT_ID: $WEBAPP_CLIENT_ID
      WEBAPP_CLIENT_SECRET: $WEBAPP_CLIENT_SECRET
      REDIS_URI: redis://redis:6379

  redis:
    image: redis:6
    ports:
      - "6379:6379"
