version: "3.9"

##
# A containerised local development environment similar to the deployed environment
#
# ! Requires Docker Desktop to be configured with 4GB of RAM !
##

services:
  postgres:
    image: library/postgres:12
    environment:
      POSTGRES_USER: beacons_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beacons
    ports:
      - "5432:5432"

  opensearch:
    image: opensearchproject/opensearch:1.1.0
    environment:
      - discovery.type=single-node
    volumes:
      - ./opensearch/opensearch.dev.yml:/usr/share/opensearch/config/opensearch.yml
    expose:
      - 9200 # Core OpenSearch queries
      - 9600 # Performance Analyzer queries
    ports: # Exposed only for local development with a non-Dockerized Spring; these ports are private when deployed
      - "9200:9200"
      - "9600:9600"

  # Client queries to OpenSearch from the public internet are authenticated using Azure AD and proxied through to
  # OpenSearch for security.
  opensearch-proxy:
    build: ./opensearch/proxy
    ports:
      - "8081:80"
    environment:
      OPENSEARCH_DOMAIN: "opensearch:9200"
      OPENSEARCH_PROTOCOL: "http"
      LOCAL: "true"
      APPLICATION_CREDENTIALS_BASE64: "" # Not used in local development

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.1.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-proxy"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"

  service:
    build:
      context: ./service
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beacons
      SPRING_PROFILES_ACTIVE: dev,seed
      OPENSEARCH_ENDPOINT: opensearch
      EXPORT_DIRECTORY: /var/export
    volumes:
      - /tmp/beacons:/var/export

  backoffice:
    build:
      context: ./backoffice
      args:
        feedback_email_addresses: dev@mcga.gov.uk,dev@madetech.com
    ports:
      - "3001:80"
    environment:
      AZURE_AD_TENANT_ID: "513fb495-9a90-425b-a49a-bc6ebe2a429e"
      AZURE_AD_CLIENT_ID: "5cdcbb41-958a-43b6-baa1-bbafd80b4f70"
      REACT_APP_FEEDBACK_EMAIL_ADDRESSES: "x@y.com,y@z.com"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # webapp:
  #   Run the Webapp application using npm from the webapp/ dir
