version: "3.8"

services:
  postgres:
    image: library/postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: beacons_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beacons
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:1.1.0
    environment:
      - discovery.type=single-node
    volumes:
      - ./opensearch/opensearch.dev.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - "9200:9200" # Core OpenSearch queries
      - "9600:9600" # Performance Analyzer queries
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 12

  # Client queries to OpenSearch from the public internet are authenticated using Azure AD and proxied through to
  # OpenSearch for security.
  opensearch-proxy:
    build: ./opensearch/proxy
    ports:
      - "8081:80"
    environment:
      OPENSEARCH_URI: "opensearch:9200"
    depends_on:
      - opensearch
    expose:
      - "8081"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.1.0
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # Communicate with OpenSearch Proxy from outside the Docker network, as if on public Internet
      OPENSEARCH_HOSTS: '["http://opensearch-proxy"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch-proxy

  beacons-service:
    build:
      context: ./service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - opensearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beacons

  backoffice:
    build:
      context: ./backoffice
    ports:
      - "3000:3000"
    depends_on:
      - beacons-service
      - opensearch
    volumes:
      - ./backoffice/src:/app/src # Enable hot reloading
