version: "3.8"

services:
  webapp:
    build:
      context: .
      target: nextjs-app
      args:
        git_hash: git_hash
        api_url: http://localhost:8080/api

    ports:
      - "3000:3000"
