spring:
  profiles:
    active: default
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/beacons}
    username: ${SPRING_DATASOURCE_USER:beacons_service}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: https://login.microsoftonline.com/513fb495-9a90-425b-a49a-bc6ebe2a429e/wsfed

server:
  servlet:
    context-path: /spring-api

beacons:
  openapi:
    github:
      url: https://github.com/mcagov/beacons-service
  cors:
    allowedOrigins: ${BEACONS_CORS_ALLOWED_ORIGINS:*}

azure:
  activedirectory:
    client-id: fedbd6b5-e88a-4cc7-86dc-06cb2f3b35d4
    app-id-uri: api://fedbd6b5-e88a-4cc7-86dc-06cb2f3b35d4
