spring:
  profiles:
    active: default
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/beacons}
    username: ${SPRING_DATASOURCE_USER:beacons_service}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /spring-api

beacons:
  openapi:
    github:
      url: https://github.com/mcagov/beacons-service
  cors:
    allowedOrigins: ${BEACONS_CORS_ALLOWED_ORIGINS:*}

azure:
  activedirectory:
    client-id: ${AZURE_AD_API_CLIENT_ID:fedbd6b5-e88a-4cc7-86dc-06cb2f3b35d4}
    app-id-uri: ${AZURE_AD_API_ID_URI:api://fedbd6b5-e88a-4cc7-86dc-06cb2f3b35d4}
