opensearch:
  source:
    host: ${OPENSEARCH_ENDPOINT:localhost}
    port: ${OPENSEARCH_PORT:9200}
    https: false
  credentials:
    enabled: false

export:
  directory:
    ${EXPORT_DIRECTORY:/tmp/beacons/export}
