opensearch:
  source:
    host: ${OPENSEARCH_ENDPOINT:localhost}
    port: ${OPENSEARCH_PORT:9200}
    https: false
  credentials:
    enabled: true
    user: ${OPENSEARCH_USER:user}
    password: ${OPENSEARCH_PASSWORD:password}
