name: Main CI/CD pipeline for MCA webapp
on:
  push:
    branches:
      - github-actions

jobs:
  install_dependencies:
    name: Npm install dependencies

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: will-work

  run_tests:
    needs: install_dependencies

    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: will-work

      - name: Run tests
        run: npm run test

  run_linting:
    needs: install_dependencies

    name: Run linter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: will-work

      - name: Run tests
        run: npm run lint
