name: Beacons Service CI/CD Pipeline

on:
  push:
    branches:
      - feature/github-actions

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit tests
        run: ./gradlew clean test

  integration_test:
    name: Integration test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: beacons-service
          POSTGRES_DB: beacons
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Integration tests
        run: ./gradlew clean integrationTest
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beacons

  docker_lint:
    name: Docker lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker lint
        uses: brpaz/hadolint-action@v1.2.1

  codeql_check:
    name: CodeQL check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile code
        run: ./gradlew clean assemble
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1