name: CI/CD Pipeline

on: [workflow_dispatch, push]

jobs:
  terraform_lint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Lint
        run: terraform fmt --recursive --check terraform

  terraform_apply:
    if: github.ref == 'refs/heads/main'
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform plan
          terraform apply -auto-approve