name: CI/CD pipeline
on: push

jobs:
  install_dependencies:
    if: github.ref == 'refs/heads/main'
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  docker_build:
    if: true == false
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Extract branch name
        shell: bash
        run: REF=${GITHUB_REF#refs/heads/} && arrREF=(${REF//// }) && echo "##[set-output name=branch;]$(echo ${arrREF[-1]})"
        id: extract_branch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to ECR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and Push
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}

  unit_tests:
    if: true == false
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: npm run test

  end_to_end_tests:
    name: End to end tests
    runs-on: ubuntu-latest
    env:
      WEBAPP_CLIENT_SECRET: ${{ secrets.WEBAPP_CLIENT_SECRET }}

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: beacons_service
          POSTGRES_DB: beacons
        ports:
          - 5432:5432
      api:
        image: 232705206979.dkr.ecr.eu-west-2.amazonaws.com/beacons-service:57a50d0ac5c0b405294cfa2084b7287c424adab1
        credentials:
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beacons
        ports:
          - 8080:8080

    steps:
      - name: Checkout webapp
        uses: actions/checkout@v2.3.4
        with:
          path: webapp
      - name: Checkout service
        uses: actions/checkout@v2.3.4
        with:
          repository: mcagov/beacons-service
          path: service

  lint_check:
    if: true == false
    name: Lint check
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run linter
        run: npm run lint

  prettier_check:
    if: true == false
    name: Prettier check
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run prettier
        run: npm run format:check

  docker_lint:
    if: true == false
    name: Docker lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Docker lint
        uses: brpaz/hadolint-action@v1.5.0

  codeql_check:
    if: true == false
    name: CodeQL check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  deploy_dev:
    if: github.ref == 'refs/heads/main'
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    needs:
      [
        install_dependencies,
        docker_build,
        unit_tests,
        end_to_end_tests,
        lint_check,
        prettier_check,
        docker_lint,
        codeql_check,
      ]

    steps:
      - name: Trigger Integration Pipeline
        run: |
          curl -X POST  -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.MCA_GITHUB_TOKEN }}" \
            https://api.github.com/repos/mcagov/beacons-integration/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main", "inputs": {"updateImageTags": "true"}}'
