name: CI/CD pipeline
on: push

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  end_to_end_tests:
    name: End to end tests
    runs-on: ubuntu-latest
    env:
      WEBAPP_CLIENT_SECRET: ${{ secrets.WEBAPP_CLIENT_SECRET }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    outputs:
      service_commit_hash: ${{ steps.get_service_commit_hash.outputs.service_commit_hash }}

    steps:
      - name: Checkout Service repo
        uses: actions/checkout@v2.3.4
        with:
          repository: "mcagov/beacons-service"
      - id: get_service_commit_hash
        name: Get commit hash from Service repo
        run: echo "::set-output name=service_commit_hash::$(git rev-parse HEAD)"
      - name: Checkout webapp repo
        uses: actions/checkout@v2.3.4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Bring up API and DB
        run: |
          SERVICE_COMMIT_HASH=${{ steps.get_service_commit_hash.outputs.service_commit_hash }} docker-compose --file docker-compose.e2e.yml up --detach
      - name: Copy env vars
        run: cp .env.example .env.local
      - name: Run Cypress end to end tests
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/endToEnd/*
          browser: chrome
          start: npm run start
          build: npm run build
          wait-on: "http://localhost:8080"

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
      - name: Stop containers
        if: always()
        run: docker-compose --file "docker-compose.e2e.yml" down

  deploy_dev:
    if: github.ref == 'refs/heads/main'
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    needs: [install_dependencies, end_to_end_tests]

    steps:
      - name: Trigger Integration Pipeline
        run: |
          curl -X POST  -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.MCA_GITHUB_TOKEN }}" \
            https://api.github.com/repos/mcagov/beacons-integration/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main", "inputs": {"updateImageTags": "true"}}'
