name: Beacons Service CI/CD Pipeline

on:
  push:
    branches:
      - feature/github-actions

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      name: Unit tests
      - run: ./gradlew clean test