name: Main CI/CD pipeline for MCA webapp
on:
  push:
    branches:
      - github-actions

jobs:
  build:
    name: Npm install dependencies

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: will-work

  run_tests:
    needs: build

    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: will-work

      - name: Run tests
        run: npm run test
