name: CI/CD Pipeline

on: [workflow_dispatch, push]

jobs:
  terraform_lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Lint
        run: terraform fmt --recursive --check

  get_docker_image_tags:
    name: Get Docker image tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'madetech/mca-beacons-webapp'
      - name: get_commit_hash
        run: git rev-parse HEAD

  print_output_from_get_docker_image_tags_job:
    runs-on: ubuntu-latest
    needs: [get_docker_image_tags]
    steps:
      - run: echo ${{needs.get_docker_image_tags.outputs.webapp_hash}}

  terraform_deploy:
    needs: [terraform_lint]
    if: github.ref == 'refs/heads/main'
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Deploy
        run: terraform apply -auto-approve
