name: Deploy to production

on:
  release:
    types:
      - released

jobs:
  deploy_production:
    name: Production (plan)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      terraform_workspace: production
      webapp_image_tag: ${{ github.event.release.tag_name }}
      service_image_tag: ${{ github.event.release.tag_name }}
      opensearch_proxy_image_tag: ${{ github.event.release.tag_name }}
      trello_list_id: 6157064b4d7e1b3b1ea839ad
    secrets:
      alert_email_address: ${{ secrets.ALERT_EMAIL_ADDRESS }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      db_password: ${{ secrets.DB_PASSWORD }}
      gov_notify_api_key: ${{ secrets.GOV_NOTIFY_API_KEY }}
      webapp_azure_ad_client_secret: ${{ secrets.WEBAPP_CLIENT_SECRET }}
      webapp_azure_b2c_client_secret: ${{ secrets.AZURE_B2C_CLIENT_SECRET }}
      webapp_azure_b2c_next_auth_jwt_secret: ${{ secrets.JWT_SECRET }}
      service_basic_auth_username: ${{ secrets.SERVICE_BASIC_AUTH_USERNAME }}
      service_basic_auth_password: ${{ secrets.SERVICE_BASIC_AUTH_PASSWORD }}
      aws_account_number: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      trello_api_key: ${{ secrets.TRELLO_API_KEY }}
      trello_token: ${{ secrets.TRELLO_TOKEN }}
      opensearch_master_user_name: ${{ secrets.OPENSEARCH_USERNAME }}
      opensearch_master_user_password: ${{ secrets.OPENSEARCH_PASSWORD }}
      opensearch_dashboards_sso_client_secret: ${{ secrets.OPENSEARCH_DASHBOARDS_SSO_CLIENT_SECRET }}