name: Deploy to production

on:
  release:
    types:
      - released

jobs:
  deploy_production:
    name: Deploy / Production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "I would have deployed release with tag ${{ github.event.release.tag_name }} to production"