name: Publish OpenSearch proxy image

on:
  workflow_call:
    inputs:
      tag:
        description: The tag to add to the published Docker image, e.g. "v1.0.1"
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  publish_opensearch_proxy_image:
    name: Publish OpenSearch proxy image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to ECR
        uses: docker/login-action@v1.10.0
        with:
          registry: 232705206979.dkr.ecr.eu-west-2.amazonaws.com
          username: ${{ secrets.aws_access_key_id }}
          password: ${{ secrets.aws_secret_access_key }}
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./terraform/opensearch-proxy
          push: true
          tags: 232705206979.dkr.ecr.eu-west-2.amazonaws.com/opensearch-proxy:${{ inputs.tag }}
