name: Staging Deployment

on: workflow_dispatch

jobs:
  terraform_plan:
    name: Terraform plan
    runs-on: ubuntu-latest

    steps:
      - name: Terraform plan
        run: echo "TODO Terraform plan"
